#!/bin/bash

set -e

$INPUT_ARTIFACTS_DIR/weak/qbt_fringe.wrapper_generator.release/strong/qbt_fringe.wrapper_generator.release/bin/wrapper_generator $INPUT_ARTIFACTS_DIR/weak/qbt_fringe.wrapper_generator.main/strong $OUTPUT_ARTIFACTS_DIR \
    wrapper_generator qbt.fringe.wrapper_generator.Main \

